### ISSUE TITLE
need help on org.xml.sax.SAXParseException

### ISSUE THREAD

**Issue by jeffpeiyt** [highsource/confluence-to-markdown-converter#2]
Hi Alexey,

our storage xml from confluence wiki has  `<ac:link></ac:link>`

Got this issue during conversion. Would you mind helping to take a look at it and give some suggestion?

thanks!

Error on line 1 column 93 of source.txt:
  SXXP0003: Error reported by XML parser: The prefix "ac" for element "ac:link" is not bound.
org.xml.sax.SAXParseException; systemId: file:/Users/ypei/Git/opensource/confluence-to-markdown-converter/bin/source.txt; lineNumber: 1; columnNumber: 93; The prefix "ac" for element "ac:link" is not bound.

**Comment by highsource** [comment]
I don't remember exactly how I did it. I think I had to fix XML a bit prior to transformation.

I had to add this fragment before:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ac:confluence SYSTEM "../../dtd/confluence-all.dtd" [
<!ENTITY clubs    "&#9827;">
<!ENTITY nbsp   "&#160;">
<!ENTITY ndash   "&#8211;">
<!ENTITY mdash   "&#8212;">
]>
<ac:confluence xmlns:ac="http://www.atlassian.com/schema/confluence/4/ac/" xmlns:ri="http://www.atlassian.com/schema/confluence/4/ri/" xmlns="http://www.atlassian.com/schema/confluence/4/">
```

And this fragment after the exported storage format:

```
</ac:confluence>
```

`"../../dtd/confluence-all.dtd"` should point to the included `confluence-all.dtd`.

I wrote this XSLT a while ago to migrate Jsonix documentation from [Confluence](http://confluence.highsource.org/display/JSNX/Jsonix) to [GitHub](https://github.com/highsource/jsonix/wiki). That worked somehow - not perfectly but well enough to give some basis and I've manually fixed pages later on.

**Comment by highsource** [comment]
Hope this helps.

**Comment by jeffpeiyt** [comment]
@highsource yeah, this works, thanks so much! the wiki API returned storage content we use do not have this wrapper. 

``` xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ac:confluence SYSTEM "/Users/ypei/Git/opensource/confluence-to-markdown-converter/dtd/confluence-all.dtd" [
<!ENTITY clubs    "&#9827;">
<!ENTITY nbsp   "&#160;">
<!ENTITY ndash   "&#8211;">
<!ENTITY mdash   "&#8212;">
]>
<ac:confluence xmlns:ac="http://www.atlassian.com/schema/confluence/4/ac/" xmlns:ri="http://www.atlassian.com/schema/confluence/4/ri/" xmlns="http://www.atlassian.com/schema/confluence/4/">


storage content

</ac:confluence>

```
